c1-digger:
  enabled: true
  image:
    imagePullSecrets:
      - name: regcred-webgl
  podLifecycle:
    terminationGracePeriodSeconds: 60
  quickConfigs:
    registry: registry.ftech.ai/webgl-game/c1-digger
    healthcheckPath: /
    port: 80
  extraLabels:
    owner: HuyVQ
    pic: IS.HuyVQ
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 5
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    hosts:
      - host: c1-digger.local.ftech.ai
        paths:
          - /:Prefix
  serviceAccount:
    create: true
    name: c1-digger
  vault:
    enabled: false
    config:
      path: secret/data/projects/is-chart/get-domains/dev
      authPath: auth/kubernetes-dev
      role: is-chart-get-domains-dev-ro
      serviceServer: https://vault-raft.prod.ftech.ai
    template:
      name: config.env
      content: |
        {{- with secret "secret/data/projects/is-chart/get-domains/dev" -}}
        {{- range $key, $value := .Data.data }}
        export {{ $key }}={{ $value }}
        {{- end }}
        {{- end }}
    runContainer:
      command:
        - /bin/bash
        - -c
      runtimeArgs:
        - source /vault/secrets/config.env && python3 http-server.py
