{{- define "poly.v3.sa" -}}
{{- $app := $.currentApp -}}
{{- $sa := $app.serviceAccount -}}
{{- if and $app.enabled (and $sa.create (not $sa.existingServiceAccount)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "poly.v3.serviceAccountName" $ }}
  labels: {{- include "poly.v3.labels" $ | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- include "poly.v3.tpl-dict" (dict "ctx" $ "dict" .) | indent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $sa.automountServiceAccountToken }}
{{- end }}
{{ end }}
