{{- define "poly.v3.statefulset" }}
{{- $app := $.currentApp -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata: {{- include "poly.v3.commonMetadata" $ | nindent 2 }}
spec:
  serviceName: {{ include "poly.v3.fullname" $ }}
  selector: {{- include "poly.v3.labelSelector" $ | nindent 4 }}
  template: {{- include "poly.v3.podTemplate" $ | nindent 4 }}
  updateStrategy: {{- include "poly.v3.updateStrategy" $ | nindent 4 }}
  {{- if not $app.autoscaling.enabled }}
  replicas: {{ if $app.rollout.enabled }}{{ 0 }}{{ else }}{{ $app.replicas }}{{ end }}
  {{- end }}
  {{- with $.currentApp.workloadCommonConfigs.statefulset -}}{{- toYaml . | nindent 2 }}{{- end -}}
{{ end }}
